/*
 * Watson Data API
 * You can use a collection of Watson Data REST APIs associated with Watson
 * Studio and Watson Knowledge Catalog to manage data-related assets and
 * connections in analytics projects and catalogs on IBM Cloud Pak for Data. Use
 * the catalog and asset APIs to create catalogs to administer your assets,
 * associate properties with those assets, and organize the users who use the
 * assets. Assets can be notebooks or connections to files, database sources, or
 * data assets from a connection.  Use the governance and workflows APIs to
 * implement data policies and a business glossary that fits to your
 * organization to control user access rights to assets and to uncover data
 * quality and data lineage.  Use the discovery, search, and connections APIs to
 * add and find data within your projects and catalogs.
 *
 * The version of the OpenAPI document: 2.35.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package com.ibm.watson.data.client.model.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * state that a Streams Flow can be in
 */
public enum StreamsFlowState {

  STARTING("starting"),

  RUNNING("running"),

  STOPPING("stopping"),

  STOPPED("stopped");

  private String value;

  StreamsFlowState(String value) { this.value = value; }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static StreamsFlowState fromValue(String value) {
    for (StreamsFlowState b : StreamsFlowState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
