# This workflow will publish an updated snapshot to Maven Central when any change is merged to master

name: "Build"

# Trigger after code is merged. only on main repo
# - does not run on modification (may be just text)

on:
  push:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Merge master"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
        # Only for a merge
        if: ${{ github.event_name == 'push' && github.repository == 'IBM/watson-data-api-clients' }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          # Java 11 is used for merge builds (PRs do check Java latest)
          java-version: '11'
          distribution: 'adopt'
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Build and publish - but only for master
      - name: Build with Maven (Publish snapshots to maven central)
        if: ${{ github.repository == 'IBM/watson-data-api-clients' && github.ref == 'refs/heads/master'}}
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: 'mvn -B -DuseMavenCentral clean deploy --file java/pom.xml'
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to 
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          # Build and publish - but only for master
      - name: Build with Maven (no snapshots published)
        if: ${{ github.repository != 'IBM/watson-data-api-clients' || github.ref != 'refs/heads/master'}}
        run: 'mvn -B clean verify --file java/pom.xml'

