# This workflow will publish to Maven Central when a release is created

name: Publish release to Maven Central

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: java

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java
    steps:
    - uses: actions/checkout@v2
    - name: Install Java and Maven
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Publish to Maven Central
      uses: samuelmeuli/action-maven-publish@v1
      with:
        directory: java
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.OSSRH_USERNAME }}
        nexus_password: ${{ secrets.OSSRH_TOKEN }}

